package com.morse.core.ui_models

import androidx.compose.runtime.mutableStateOf

data class Source(
    val key: String,
    var name: String,
) {
    val isSelected = mutableStateOf(false)

    companion object All {
        fun get() = listOf(Source(key = "abc-news", name = "ABC News"),
            Source(key = "abc-news-au", name = "ABC News (AU)"),
            Source(key = "aftenposten", name = "Aftenposten"),
            Source(key = "al-jazeera-english", name = "Al Jazeera English"),
            Source(key = "ansa", name = "ANSA.it"),
            Source(key = "argaam", name = "Argaam"),
            Source(key = "ars-technica", name = "Ars Technica"),
            Source(key = "ary-news", name = "Ary News"),
            Source(key = "associated-press", name = "Associated Press"),
            Source(key = "australian-financial-review", name = "Australian Financial Review"),
            Source(key = "axios", name = "Axios"),
            Source(key = "bbc-news", name = "BBC News"),
            Source(key = "bbc-sport", name = "BBC Sport"),
            Source(key = "bild", name = "Bild"),
            Source(key = "blasting-news-br", name = "Blasting News (BR)"),
            Source(key = "bleacher-report", name = "Bleacher Report"),
            Source(key = "bloomberg", name = "Bloomberg"),
            Source(key = "breitbart-news", name = "Breitbart News"),
            Source(key = "business-inskeyer", name = "Business Inskeyer"),
            Source(key = "buzzfeed", name = "Buzzfeed"),
            Source(key = "cbc-news", name = "CBC News"),
            Source(key = "cbs-news", name = "CBS News"),
            Source(key = "cnn", name = "CNN"),
            Source(key = "cnn-es", name = "CNN Spanish"),
            Source(key = "crypto-coins-news", name = "Crypto Coins News"),
            Source(key = "der-tagesspiegel", name = "Der Tagesspiegel"),
            Source(key = "die-zeit", name = "Die Zeit"),
            Source(key = "el-mundo", name = "El Mundo"),
            Source(key = "engadget", name = "Engadget"),
            Source(key = "entertainment-weekly", name = "Entertainment Weekly"),
            Source(key = "espn", name = "ESPN"),
            Source(key = "espn-cric-info", name = "ESPN Cric Info"),
            Source(key = "financial-post", name = "Financial Post"),
            Source(key = "focus", name = "Focus"),
            Source(key = "football-italia", name = "Football Italia"),
            Source(key = "fortune", name = "Fortune"),
            Source(key = "four-four-two", name = "FourFourTwo"),
            Source(key = "fox-news", name = "Fox News"),
            Source(key = "fox-sports", name = "Fox Sports"),
            Source(key = "globo", name = "Globo"),
            Source(key = "google-news", name = "Google News"),
            Source(key = "google-news-ar", name = "Google News (Argentina)"),
            Source(key = "google-news-au", name = "Google News (Australia)"),
            Source(key = "google-news-br", name = "Google News (Brasil)"),
            Source(key = "google-news-ca", name = "Google News (Canada)"),
            Source(key = "google-news-fr", name = "Google News (France)"),
            Source(key = "google-news-in", name = "Google News (India)"),
            Source(key = "google-news-is", name = "Google News (Israel)"),
            Source(key = "google-news-it", name = "Google News (Italy)"),
            Source(key = "google-news-ru", name = "Google News (Russia)"),
            Source(key = "google-news-sa", name = "Google News (Saudi Arabia)"),
            Source(key = "google-news-uk", name = "Google News (UK)"),
            Source(key = "goteborgs-posten", name = "Göteborgs-Posten"),
            Source(key = "gruenderszene", name = "Gruenderszene"),
            Source(key = "hacker-news", name = "Hacker News"),
            Source(key = "handelsblatt", name = "Handelsblatt"),
            Source(key = "ign", name = "IGN"),
            Source(key = "il-sole-24-ore", name = "Il Sole 24 Ore"),
            Source(key = "independent", name = "Independent"),
            Source(key = "infobae", name = "Infobae"),
            Source(key = "info-money", name = "InfoMoney"),
            Source(key = "la-gaceta", name = "La Gaceta"),)
    }
}